services:
  automator:
    container_name: bizbuysell-automator
    build: .
    image: austinjhunt/bizbuysell:latest
    # Add volumes
    volumes:
      - ./files:/opt/data/files
    command: python lambda_function.py
    env_file: .env
